### ISSUE TITLE
KB: Dev team agenda

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/knowledgebase#11]
### Overview
This issue tracks the agenda for our weekly meetings

#### Issue Template
```
## [Date ]  Meeting Agenda

### Prework to prep for meeting
- [ ] #

### Recurring items
 - [ ] Review any questions outstanding from https://github.com/hackforla/BOP/issues/266
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/knowledgebase/projects/1#column-19676619)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Ethan Strominger](https://github.com/hackforla/knowledgebase/issues/assigned/ethanstrominger)
       - [ ] [Toe Arkar](https://github.com/hackforla/knowledgebase/issues/assigned/Toe12)
       - [ ] [Priya](https://github.com/hackforla/knowledgebase/issues/assigned/pwalia1)
       - [ ] [Erin](https://github.com/hackforla/knowledgebase/issues/assigned/erin)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items
```

### Links to other agenda issues for your team 
(so that you can easily post on their agendas items that come up at yours)
- PM agenda https://github.com/hackforla/BOP/issues/264

**Comment by ExperimentsInHonesty** [comment]
## 2023-10-31 Meeting Agenda

### Prework to prep for meeting
- [ ] Add your stories to 

### Recurring items
 - [ ] Review any questions outstanding from https://github.com/hackforla/BOP/issues/266
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/knowledgebase/projects/1#column-19676619)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Ethan Strominger](https://github.com/hackforla/knowledgebase/issues/assigned/ethanstrominger)
       - [ ] [Toe Arkar](https://github.com/hackforla/knowledgebase/issues/assigned/Toe12)
       - [ ] [Priya](https://github.com/hackforla/knowledgebase/issues/assigned/pwalia1)
       - [ ] [Erin](https://github.com/hackforla/knowledgebase/issues/assigned/erin)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by ExperimentsInHonesty** [comment]
## 2023-11-03 Meeting Agenda

### Prework to prep for meeting
- Add any questions you have here https://github.com/hackforla/BOP/issues/266

### Recurring items
 - [ ] Review any questions outstanding from https://github.com/hackforla/BOP/issues/266
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/knowledgebase/projects/1#column-19676619)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Ethan Strominger](https://github.com/hackforla/knowledgebase/issues/assigned/ethanstrominger)
       - [ ] [Toe Arkar](https://github.com/hackforla/knowledgebase/issues/assigned/Toe12)
       - [ ] [Priya](https://github.com/hackforla/knowledgebase/issues/assigned/pwalia1)
       - [ ] [Erin](https://github.com/hackforla/knowledgebase/issues/assigned/erin)

### New Items
- [ ] Add tasks to this issue #12
- [ ] Discuss logistics
- [ ] Review issues (or TODO) for assignments
- [ ] identify potential feature labels
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by ethanstrominger** [comment]
## 2023-11-03 Meeting Agenda

### Prework to prep for meeting
- Add any questions you have here https://github.com/hackforla/BOP/issues/266

### Recurring items
 - [ ] Review any questions outstanding from https://github.com/hackforla/BOP/issues/266
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/knowledgebase/projects/1#column-19676619)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Ethan Strominger](https://github.com/hackforla/knowledgebase/issues/assigned/ethanstrominger)
       - [ ] [Toe Arkar](https://github.com/hackforla/knowledgebase/issues/assigned/Toe12)
       - [ ] [Priya](https://github.com/hackforla/knowledgebase/issues/assigned/pwalia1)
       - [ ] [Erin](https://github.com/hackforla/knowledgebase/issues/assigned/erin)

### New Items
- [ ] Review figma and compare to data model
- [ ] Discuss front end developer engagement (when?)
- [ ] Knowledge transfer
   - [ ] Review Wiki structure
   - [ ] Review how table definition spreadsheet is organized
   - [ ] Review UI
   - [ ] Review Github project board
   - [ ] At next meeting (so devs can try or review first)
     - [ ] troubleshoot deployment issues 
     - [ ] review code in peopledepot/django-root (ignore util and iso-tutorial node)
- [ ] Review issues (or TODO) for assignments
- [ ]  #13 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

   

### Task Items

**Comment by ethanstrominger** [comment]
## 2023-11-10 Meeting Agenda

### Prework to prep for meeting
- Add any questions you have to #16 

### Recurring items
 - [ ] Review any questions outstanding from https://github.com/hackforla/BOP/issues/266
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/knowledgebase/projects/1#column-19676619)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Ethan Strominger](https://github.com/hackforla/knowledgebase/issues/assigned/ethanstrominger)
       - [ ] [Toe Arkar](https://github.com/hackforla/knowledgebase/issues/assigned/Toe12)
       - [ ] [Priya](https://github.com/hackforla/knowledgebase/issues/assigned/pwalia1)
       - [ ] [Erin](https://github.com/hackforla/knowledgebase/issues/assigned/erin)

### New Items
- [ ] Review figma and compare to data model
- [ ] Discuss front end developer engagement (when?)
- [ ] Add tasks to this issue #12
- [ ] Knowledge transfer
   - [ ] Review Wiki structure
   - [ ] Review how table definition spreadsheet is organized
   - [ ] Review UI
   - [ ] Review Github project board
   - [ ] At next meeting (so devs can try or review first)
     - [ ] troubleshoot deployment issues 
     - [ ] review code in peopledepot/django-root (ignore util and iso-tutorial node)
- [ ] 
- [ ] Review issues (or TODO) for assignments
- [ ]  #13 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by 1610saas** [comment]
s### Overview
This issue tracks the agenda for our weekly meetings

#### Issue Template
```
## [Date ]  Meeting Agenda

### Prework to prep for meeting
- [ ] #

### Recurring items
 - [ ] Review any questions outstanding from #18 
 - [ ] review open issues (https://github.com/hackforla/knowledgebase/issues)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Ethan Strominger](https://github.com/hackforla/knowledgebase/issues/assigned/ethanstrominger)
       - [ ] [Toe Arkar](https://github.com/hackforla/knowledgebase/issues/assigned/Toe12)
       - [ ] [Priya](https://github.com/hackforla/knowledgebase/issues/assigned/pwalia1)
       - [ ] [Erin](https://github.com/hackforla/knowledgebase/issues/assigned/erin)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items
```

### Links to other agenda issues for your team 
(so that you can easily post on their agendas items that come up at yours)
- PM agenda https://github.com/hackforla/BOP/issues/264

### Previous Meetings (link to each comment with the date)

<details><summary>2023-10-27 meeting notes</summary>

- The purpose of the BoP project is to create an app to catalog knowledge assets about development practices for Code for America brigades.
- The purpose of the Knowledgebase app which is in progress is intended to supported BoP functionality.   Additionally, the app supports the generation of web pages from markdown about development practices.   The markdown is stored in the HackForLA Website repo and when generated, added to the "Toolkit" of the HackForLA website.  The web page and source markdown are also content asset which would be of interest to HackForLA and potentially other Code for America brigades.
- Since Knowledgebase is intended to support BOP, the two projects are being combined.
- MVP for Phase 1 will only support the cataloging of content described in the first bullet.  Generation of HackForLA content will be a later phase.
- Knowledgebase stores content assets and related data in a Postgres or  (for development only) MySQL database.  The data is maintained through the default admin screens in Django.  
- The Knowledgebase screens were reviewed to see how closely they align with BOP.  The following needs to be added to the Knowledgebase model:
  - gdoc (badly named) table which was intended to hold all types of content assets will be split into two tables: asset groups and assets.  Most fields will go into asset group. An asset group will have one or more assets associated with it.  Asset table will include title, asset type, and URL at a minimum.
  - google id is only relevant if the content is used as source for the HackForLA website.  To support parallel development of web page generation this field will need to be included but can be hidden when deployed to production.
  - a field is needed to indicate this is for / from the HackForLA website, which will be hidden for production.
- Data will be initially populated from existing google sheets
- Subsequent updates and additions will be done through the Django admin page.  No APIs need to built for this.
- Viewing and querying can also be done through Django admin, depending on the complexity of the functional and usability requirements.
- Django admin security (which comes with role and group based security) will be configured based on security requirements.
- APIs will be created to support a dashboard that summarizes the asset data.
- Data maintained by People Depot will be synchronized with Knowledgebase

 </details>

**Comment by 1610saas** [comment]
## 2023-11-17 Meeting Agenda

### Prework to prep for meeting
- Add any questions the Dev team has to [https://github.com/hackforla/BOP/issues/266]

### Recurring items
 - [ ] Review any questions outstanding from [#266](https://github.com/hackforla/BOP/issues/266)
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/knowledgebase/issues)
 - [ ] Review #18 
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Ethan Strominger](https://github.com/hackforla/knowledgebase/issues/assigned/ethanstrominger)
       - [ ] [Toe Arkar](https://github.com/hackforla/knowledgebase/issues/assigned/Toe12)
       - [ ] [Priya](https://github.com/hackforla/knowledgebase/issues/assigned/pwalia1)
       - [ ] [Erin](https://github.com/hackforla/knowledgebase/issues/assigned/erin)

### New Items
- [ ] Review figma and compare to data model
- [ ] Discuss front end developer engagement (when?)
- [ ] Add tasks to this issue #12
- [ ] Knowledge transfer
   - [ ] Review Wiki structure
   - [ ] Review how table definition spreadsheet is organized
   - [ ] Review UI
   - [ ] Review Github project board
   - [ ] At next meeting (so devs can try or review first)
     - [ ] troubleshoot deployment issues 
     - [ ] review code in peopledepot/django-root (ignore util and iso-tutorial node)
- [ ] 
- [ ] Review issues (or TODO) for assignments
- [ ]  #13 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by ethanstrominger** [comment]
## 2023-11-17 Meeting Agenda

### Prework to prep for meeting
- Add any questions the Dev team has to [#266](https://github.com/hackforla/BOP/issues/266)

### Recurring items
- [ ] Designate note taker 
- [ ] Review any questions outstanding from [#266](https://github.com/hackforla/BOP/issues/266)
- [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/knowledgebase/issues)
 - [ ] Review #18 
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Ethan Strominger](https://github.com/hackforla/knowledgebase/issues/assigned/ethanstrominger)
       - [ ] [Toe Arkar](https://github.com/hackforla/knowledgebase/issues/assigned/Toe12)
       - [ ] [Priya](https://github.com/hackforla/knowledgebase/issues/assigned/pwalia1)
       - [ ] [Erin](https://github.com/hackforla/knowledgebase/issues/assigned/erin)
       - [ ] [Jenny](https://github.com/hackforla/knowledgebase/issues/assigned/ejennywhiley123)
       - [ ] [Daniel](https://github.com/hackforla/knowledgebase/issues/assigned/dxk613)

### New Items
- [ ] Review figma and compare to data model
- [x] Discuss front end developer engagement (when?)
- [ ] Add tasks to this issue #12
- [ ] Knowledge transfer
   - [ ] Review Wiki structure
   - [ ] Review how table definition spreadsheet is organized
   - [ ] Review UI
   - [ ] Review Github project board
   - [ ] At next meeting (so devs can try or review first)
     - [ ] troubleshoot deployment issues 
     - [ ] review code in peopledepot/django-root (ignore util and iso-tutorial node)
- [ ] 
- [ ] Review issues (or TODO) for assignments
- [ ]  #13 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items
