### ISSUE TITLE
## 2023-11-03 Meeting Agenda

### ISSUE THREAD

**Issue by ethanstrominger** [hackforla/knowledgebase#17]
## 2023-11-03 Meeting Agenda

### Prework to prep for meeting
- Add any questions you have here https://github.com/hackforla/BOP/issues/266

### Recurring items
 - [ ] Review any questions outstanding from https://github.com/hackforla/BOP/issues/266
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/knowledgebase/projects/1#column-19676619)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Ethan Strominger](https://github.com/hackforla/knowledgebase/issues/assigned/ethanstrominger)
       - [ ] [Toe Arkar](https://github.com/hackforla/knowledgebase/issues/assigned/Toe12)
       - [ ] [Priya](https://github.com/hackforla/knowledgebase/issues/assigned/pwalia1)
       - [ ] [Erin](https://github.com/hackforla/knowledgebase/issues/assigned/erin)

### New Items
- [ ] Review figma and compare to data model
- [ ] Knowledge transfer
   - [ ] Review Wiki structure
   - [ ] Review how table definition spreadsheet is organized
   - [ ] Review UI
   - [ ] Review Github project board
   - [ ] At next meeting (so devs can try or review first)
     - [ ] troubleshoot deployment issues 
     - [ ] review code in peopledepot/django-root (ignore util and iso-tutorial node)
- [ ] 
- [ ] Review issues (or TODO) for assignments
- [ ]  #13 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting
- Discussed / reviewed
  - code for data models to understand Django
  - requirements of API (read only)
  - started reviewing figma and mapping to Django data model, but need Bonnie
   

### Task Items

_Originally posted by @ExperimentsInHonesty in https://github.com/hackforla/knowledgebase/issues/11#issuecomment-1787641201_
